"""Command-line entry point for sva-gen."""

from pathlib import Path

import click
from rich.console import Console
from rich.panel import Panel

from sva_gen.llm_client import LLMClient
from sva_gen.parser import extract_module_name, read_rtl
from sva_gen.validator import validate_sva_syntax, verilator_available

console = Console()


@click.command()
@click.argument("rtl_file", type=click.Path(exists=True, path_type=Path))
@click.option(
    "--output-dir",
    type=click.Path(path_type=Path),
    default=Path("outputs"),
    help="Directory to write generated assertions.",
)
@click.option(
    "--model",
    default=None,
    help="Override the Claude model (default from SVA_GEN_MODEL env var).",
)
@click.option("--no-validate", is_flag=True, help="Skip Verilator syntax check.")
def main(rtl_file: Path, output_dir: Path, model: str | None, no_validate: bool) -> None:
    """Generate SystemVerilog Assertions for an RTL module using Claude."""

    console.print(Panel.fit("sva-gen - LLM-powered SVA generator", style="bold cyan"))

    # Read input
    rtl = read_rtl(rtl_file)
    module_name = extract_module_name(rtl)
    console.print(f"[green]OK[/green] Loaded module [bold]{module_name}[/bold] from {rtl_file}")

    # Generate
    console.print("[yellow]...[/yellow] Calling Claude to generate assertions...")
    client = LLMClient(model=model)
    result = client.generate(rtl)
    console.print(
        f"[green]OK[/green] Generated {len(result.properties)} properties for "
        f"[bold]{result.module_name}[/bold]"
    )

    # Compose output file
    output_dir.mkdir(parents=True, exist_ok=True)
    out_path = output_dir / f"{module_name}_assertions.sv"
    out_text = _format_output(result)
    out_path.write_text(out_text, encoding="utf-8")
    console.print(f"[green]OK[/green] Wrote {out_path}")

    # Validate
    if no_validate:
        console.print("[dim]Validation skipped (--no-validate).[/dim]")
        return

    if not verilator_available():
        console.print(
            "[yellow]![/yellow] Verilator not installed; install it to enable syntax checking."
        )
        return

    # Inject the assertions back into the original RTL so they see all
    # module-internal signals. The validator handles the actual injection.
    assertion_block = "\n\n".join(p.sva_code for p in result.properties)
    validation = validate_sva_syntax(rtl, assertion_block)
    if validation.ok:
        console.print(f"[green]OK[/green] {validation.message}")
    else:
        console.print(f"[red]ERROR[/red] {validation.message}")


def _format_output(result) -> str:
    lines = [
        f"// Auto-generated SystemVerilog Assertions for module: {result.module_name}",
        f"// Generated by sva-gen",
        f"//",
        f"// Module summary:",
    ]
    for paragraph in result.summary.splitlines():
        lines.append(f"//   {paragraph}")
    lines.append(f"//")
    lines.append(f"// Clock signal: {result.clock_signal}")
    lines.append(f"// Reset signal: {result.reset_signal}")
    if result.notes:
        lines.append(f"//")
        lines.append(f"// Notes from generator:")
        for paragraph in result.notes.splitlines():
            lines.append(f"//   {paragraph}")
    lines.append("")

    for prop in result.properties:
        lines.append(f"// ---- {prop.name} ({prop.kind}) ----")
        lines.append(f"// Description : {prop.description}")
        lines.append(f"// Justification: {prop.justification}")
        lines.append(prop.sva_code)
        lines.append("")

    return "\n".join(lines)
