// Auto-generated SystemVerilog Assertions for module: arbiter
// Generated by sva-gen — https://github.com/<your-username>/sva-gen
//
// Module summary:
//   A round-robin arbiter for N (default 4) requesters. Each cycle it scans requesters starting just after the last-granted index and grants one-hot to the first asserted request found. It records the granted index in 'last' so the next arbitration round resumes from there, providing fairness. Reset clears the grant and last pointer.
//
// Clock signal: clk
// Reset signal: rst_n (active-low, synchronous as coded)
//
// Notes from generator:
//   The 'c_all_requesters_served' cover is hard-coded for N=4 to match the default parameter. If N is overridden the cover would need adjustment. Also, the assertion p_grant_when_req_exists assumes the arbiter is never stalled by any external mechanism; it relies on the always-grant-next-cycle behaviour visible in the RTL.

// ---- p_reset_clears_grant (assert) ----
// Description : After reset, grant must be zero.
// Justification: Reset must place arbiter in a known idle state with no granted requesters.
property p_reset_clears_grant;
  @(posedge clk) (!rst_n) |=> (grant == '0);
endproperty
assert property (p_reset_clears_grant);

// ---- p_grant_onehot_or_zero (assert) ----
// Description : Grant must be one-hot or all-zero at any time.
// Justification: By construction the arbiter grants at most one requester per cycle; multiple simultaneous grants would be a fairness/correctness bug.
property p_grant_onehot_or_zero;
  @(posedge clk) disable iff (!rst_n)
    $onehot0(grant);
endproperty
assert property (p_grant_onehot_or_zero);

// ---- p_no_grant_when_no_req (assert) ----
// Description : If no requests were asserted in the previous cycle, no grant should be issued this cycle.
// Justification: The arbiter must never spuriously grant a requester that did not request.
property p_no_grant_when_no_req;
  @(posedge clk) disable iff (!rst_n)
    ($past(req) == '0) |-> (grant == '0);
endproperty
assert property (p_no_grant_when_no_req);

// ---- p_grant_implies_prior_req (assert) ----
// Description : Any bit that is granted must have been requested on the previous cycle.
// Justification: Ensures grants are always backed by an actual request, not generated arbitrarily.
property p_grant_implies_prior_req;
  @(posedge clk) disable iff (!rst_n)
    (grant != '0) |-> ((grant & $past(req)) == grant);
endproperty
assert property (p_grant_implies_prior_req);

// ---- p_grant_when_req_exists (assert) ----
// Description : If any request was asserted in the previous cycle, some grant must be issued this cycle.
// Justification: Liveness/forward-progress: a pending request must eventually be served; the design grants in the next cycle.
property p_grant_when_req_exists;
  @(posedge clk) disable iff (!rst_n)
    ($past(req) != '0) |-> (grant != '0);
endproperty
assert property (p_grant_when_req_exists);

// ---- p_last_tracks_grant (assert) ----
// Description : When a grant is issued, 'last' must equal the index of the granted bit.
// Justification: The round-robin pointer must accurately record the most-recently granted requester; otherwise fairness is broken.
property p_last_tracks_grant;
  @(posedge clk) disable iff (!rst_n)
    (grant != '0) |-> (grant[last] == 1'b1);
endproperty
assert property (p_last_tracks_grant);

// ---- c_round_robin_rotation (cover) ----
// Description : Cover that two different requesters get granted on consecutive cycles, exercising rotation.
// Justification: Demonstrates the arbiter actually rotates among requesters rather than sticking on one.
property c_round_robin_rotation;
  @(posedge clk) disable iff (!rst_n)
    (grant != '0) ##1 (grant != '0) and (grant != $past(grant));
endproperty
cover property (c_round_robin_rotation);

// ---- c_all_requesters_served (cover) ----
// Description : Cover that each of the N requesters has been granted at some point.
// Justification: Coverage of full fairness: confirms in simulation that every requester is reachable as a winner.
property c_all_requesters_served;
  @(posedge clk) disable iff (!rst_n)
    (grant[0]) ##[1:$] (grant[1]) ##[1:$] (grant[2]) ##[1:$] (grant[3]);
endproperty
cover property (c_all_requesters_served);
