// Auto-generated SystemVerilog Assertions for module: fifo
// Generated by sva-gen — https://github.com/<your-username>/sva-gen
//
// Module summary:
//   A parameterised synchronous FIFO with configurable DEPTH and WIDTH. It uses write and read pointers plus an explicit count register to track occupancy. Empty and full flags are derived from count. Pushes are ignored when full and pops are ignored when empty; simultaneous push and pop are supported and keep count unchanged. Reset is synchronous and active-low, clearing both pointers and count.
//
// Clock signal: clk
// Reset signal: rst_n (active-low, synchronous)
//
// Notes from generator:
//   Data-integrity (FIFO ordering of dout values vs. pushed din) is not asserted here because it requires auxiliary modelling (e.g., a reference queue) that goes beyond the simple SVA subset requested. The properties above focus on control-path correctness.

// ---- p_reset_state (assert) ----
// Description : After synchronous reset, pointers and count are zero, so the FIFO is empty and not full.
// Justification: Reset must bring the FIFO to a known empty state; otherwise downstream reads/writes are undefined.
property p_reset_state;
  @(posedge clk) (!rst_n) |=> (count == 0 && wr_ptr == 0 && rd_ptr == 0 && empty && !full);
endproperty
assert property (p_reset_state);

// ---- p_count_in_range (assert) ----
// Description : Count never exceeds DEPTH.
// Justification: Count overflow would corrupt the full/empty flags and break flow control.
property p_count_in_range;
  @(posedge clk) disable iff (!rst_n) (count <= DEPTH);
endproperty
assert property (p_count_in_range);

// ---- p_empty_full_exclusive (assert) ----
// Description : Empty and full are never asserted simultaneously (assuming DEPTH > 0).
// Justification: Both flags high simultaneously would indicate a fundamental bookkeeping error.
property p_empty_full_exclusive;
  @(posedge clk) disable iff (!rst_n) !(empty && full);
endproperty
assert property (p_empty_full_exclusive);

// ---- p_push_only_increments (assert) ----
// Description : A push without a concurrent pop, when not full, increments count by 1.
// Justification: Verifies basic write accounting; a bug here causes data loss or false full/empty.
property p_push_only_increments;
  @(posedge clk) disable iff (!rst_n)
    (push && !pop && !full) |=> (count == $past(count) + 1);
endproperty
assert property (p_push_only_increments);

// ---- p_pop_only_decrements (assert) ----
// Description : A pop without a concurrent push, when not empty, decrements count by 1.
// Justification: Verifies basic read accounting; a bug here causes under/overflow of count.
property p_pop_only_decrements;
  @(posedge clk) disable iff (!rst_n)
    (pop && !push && !empty) |=> (count == $past(count) - 1);
endproperty
assert property (p_pop_only_decrements);

// ---- p_simul_push_pop_holds (assert) ----
// Description : Simultaneous push and pop leave count unchanged (when neither blocked).
// Justification: Concurrent push/pop is a classic FIFO corner case where count often drifts due to off-by-one bugs.
property p_simul_push_pop_holds;
  @(posedge clk) disable iff (!rst_n)
    (push && pop && !full && !empty) |=> (count == $past(count));
endproperty
assert property (p_simul_push_pop_holds);

// ---- p_no_change_when_idle (assert) ----
// Description : When neither effective push nor effective pop occurs, count is preserved.
// Justification: Ensures the FIFO never spuriously changes occupancy, including when push-on-full or pop-on-empty are correctly ignored.
property p_no_change_when_idle;
  @(posedge clk) disable iff (!rst_n)
    (!(push && !full) && !(pop && !empty)) |=> (count == $past(count));
endproperty
assert property (p_no_change_when_idle);

// ---- c_fill_then_drain (cover) ----
// Description : Coverage: the FIFO can become full and subsequently become empty again.
// Justification: Demonstrates that the testbench actually exercises the FIFO across its full operating range.
property c_fill_then_drain;
  @(posedge clk) disable iff (!rst_n)
    full ##[1:$] empty;
endproperty
cover property (c_fill_then_drain);
