// Auto-generated SystemVerilog Assertions for module: uart_tx
// Generated by sva-gen — https://github.com/<your-username>/sva-gen
//
// Module summary:
//   A minimal 8-N-1 UART transmitter with a configurable baud rate divisor. When 'start' is asserted in IDLE, it latches the input byte, drops the tx line for a start bit, shifts out 8 data bits LSB-first at the configured baud rate, then drives a stop bit high before returning to IDLE. The 'busy' output is held high for the entire transmission.
//
// Clock signal: clk
// Reset signal: rst_n (active-low, synchronous in this design)
//
// Notes from generator:
//   State encoding values (IDLE=0, START_BIT=1, DATA_BITS=2, STOP_BIT=3) are taken from the declaration order of the enum. Reset is treated as synchronous since the always_ff is only sensitive to posedge clk; the disable iff still works correctly because rst_n low forces the reset state on the next clock. A property asserting that 'start' is ignored while busy was considered but is implicit in the FSM (only IDLE checks start), and proving it would require asserting that state stays unchanged on start during non-IDLE, which is already covered by the state-machine determinism.

// ---- p_reset_state (assert) ----
// Description : After reset, the transmitter is idle, tx line is high, and busy is low.
// Justification: UART line must idle high after reset; otherwise downstream receivers see spurious start bits.
property p_reset_state;
  @(posedge clk) (!rst_n) |=> (state == 2'd0) && (tx == 1'b1) && (busy == 1'b0);
endproperty
assert property (p_reset_state);

// ---- p_idle_tx_high (assert) ----
// Description : Whenever the FSM is in IDLE and not starting a transmission, tx must be high and busy must be low.
// Justification: Idle line level for UART must be high; ensures the transmitter holds line state correctly between frames.
property p_idle_tx_high;
  @(posedge clk) disable iff (!rst_n)
    (state == 2'd0) && !start |=> (tx == 1'b1) && (busy == 1'b0);
endproperty
assert property (p_idle_tx_high);

// ---- p_start_triggers_busy (assert) ----
// Description : Asserting start while idle causes busy to go high and tx to be driven low (start bit) on the next cycle.
// Justification: Verifies the handshake between start and the beginning of a UART frame, which is the fundamental TX trigger.
property p_start_triggers_busy;
  @(posedge clk) disable iff (!rst_n)
    (state == 2'd0) && start |=> (busy == 1'b1) && (tx == 1'b0) && (state == 2'd1);
endproperty
assert property (p_start_triggers_busy);

// ---- p_busy_during_tx (assert) ----
// Description : Whenever the FSM is in any non-IDLE state, busy must be asserted.
// Justification: External logic relies on busy to know it cannot issue a new byte; busy must accurately reflect transmit activity.
property p_busy_during_tx;
  @(posedge clk) disable iff (!rst_n)
    (state != 2'd0) |-> (busy == 1'b1);
endproperty
assert property (p_busy_during_tx);

// ---- p_stop_bit_high (assert) ----
// Description : While in the STOP_BIT state, the tx line must be high.
// Justification: A stop bit is defined as a high level on the line; failing this means the frame is malformed.
property p_stop_bit_high;
  @(posedge clk) disable iff (!rst_n)
    (state == 2'd3) |-> (tx == 1'b1);
endproperty
assert property (p_stop_bit_high);

// ---- p_baud_cnt_in_range (assert) ----
// Description : The baud counter never exceeds BAUD_DIV-1.
// Justification: Ensures the baud counter is always reloaded with the correct value and never wraps unexpectedly, which would corrupt bit timing.
property p_baud_cnt_in_range;
  @(posedge clk) disable iff (!rst_n)
    (baud_cnt <= (BAUD_DIV - 1));
endproperty
assert property (p_baud_cnt_in_range);

// ---- p_bit_idx_bound (assert) ----
// Description : The data-bit index never exceeds 7 while in DATA_BITS.
// Justification: Guards against out-of-range bit indexing which would imply incorrect frame length.
property p_bit_idx_bound;
  @(posedge clk) disable iff (!rst_n)
    (state == 2'd2) |-> (bit_idx <= 3'd7);
endproperty
assert property (p_bit_idx_bound);

// ---- c_full_frame_completes (cover) ----
// Description : Coverage: the FSM reaches the STOP_BIT state, demonstrating a complete transmission path.
// Justification: Liveness check: testbench must exercise an end-to-end frame to consider the TX verified.
property c_full_frame_completes;
  @(posedge clk) disable iff (!rst_n)
    (state == 2'd3);
endproperty
cover property (c_full_frame_completes);
